<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("CHANGE_PASSWORD"));
?>

	
			
				<div class="main-content-login">
					<?php 
						echo $this->render('bloglogo.phtml');
					?>
					<div class="row">
						<div class="content-login">
							<div class="row row-control">
								<div class="col-12 col-sm-3 col-md-3">
								</div>
								<div class="col-12 col-sm-6 col-md-6">
									<div class="row">
										<div class="col-md-12 col-sm-12 col-xs-12 content-page-title">
											<h3 class="page-title"><span class="glyphicon glyphicon-wrench"></span> <span class="sp-title"><?php echo $tr->translate("CHANGE_PASSWORD")?></span></h3>
											<h5 id ="messagescan" class="message_scan"><?php echo $this->msg; ?></h5>
										</div>
									</div>
									<form method="post">
									<div class="form-group">
										<label for="exampleInputEmail1"><?php echo $tr->translate("CURRENT_PASSWORD")?></label>
										<input type="password" required="required" class="form-control" id="password"  name="password" placeholder="<?php echo $tr->translate("CURRENT_PASSWORD")?>">
									  </div>
									  <div class="form-group">
										<label for="exampleInputPassword1"><?php echo $tr->translate("NEW_PASSWORD")?></label>
										<input type="password" required="required" class="form-control" id="new_password"  name="new_password" placeholder="<?php echo $tr->translate("PASSWORD")?>">
									  </div>
									  <div class="form-group">
										<label for="exampleInputPassword1"><?php echo $tr->translate("COMFIRM_PASSWORD")?></label>
										<input type="password" required="required" class="form-control" id="new_con_password"  name="new_con_password" placeholder="<?php echo $tr->translate("PASSWORD")?>">
									  </div>
									  <div class="form-group text-center">
										 <button type="submit" id="submit-button" class="btn btn-primary btn-login"><span class="glyphicon glyphicon-floppy-saved"></span> <?php echo $tr->translate("SAVE")?></button>
									  </div>
									 </form>
								</div>
								<div class="col-12 col-sm-3 col-md-3">
								</div>
							</div>
						</div>
						<div>
					</div>
				</div>
			</div>	
			<script>
			$("#new_con_password").keyup(function(){
				 var cNewPss =$( "#new_con_password" ).val();
				 var newPss =$( "#new_password" ).val();
				 $( "#messagescan" ).html('');
				 if(cNewPss != newPss){
					 $( "#messagescan" ).html('<?php echo $tr->translate("NEW_PASSWOR_NOT_MATCH")?>');
					 $('#submit-button').prop('disabled', true);
				 }else{
					 $('#submit-button').prop('disabled', false);
				 }
				});
			
			</script>
	

		
	