<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("HOME"));
?>

	
			
					<?php 
						echo $this->render('bloglogo.phtml');
					?>
					<div class="row">
						<div class="content-button">
							<div class="row row-button">
								<div class="col-12 col-sm-4 col-md-4">
									<a class="btn button-scan scan-receive" href="<?php echo $this->baseUrl()."/index/scan-receive"?>">
										<span class="glyphicon glyphicon-qrcode"></span><br />
										<?php echo $tr->translate("SCAN_RECEIVE")?>
									</a>
								</div>
								<div class="col-12 col-sm-4 col-md-4">
									<a class="btn button-scan scan-view" href="<?php echo $this->baseUrl()."/index/scan-view"?>">
										<span class="glyphicon glyphicon-qrcode"></span><br />
										<?php echo $tr->translate("SCAN_VIEW")?>
									</a>
								</div>
								<div class="col-12 col-sm-4 col-md-4">
									<a class="btn button-scan scan-close" href="<?php echo $this->baseUrl()."/index/scan-close"?>">
										<span class="glyphicon glyphicon-qrcode"></span><br />
										<?php echo $tr->translate("SCAN_CLOSE")?>
									</a>
								</div>
							</div>
							<div class="clearfix"></div>
						</div>
						<div>
					</div>
				</div>
		
	
	
	

