<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("LOGIN"));
?>

	
			
				<div class="main-content-login">
					<?php 
						echo $this->render('bloglogo.phtml');
					?>
					<div class="row">
						<div class="content-login">
							<div class="row row-control">
								<div class="col-12 col-sm-3 col-md-3">
								</div>
								<div class="col-12 col-sm-6 col-md-6">
									<form method="post">
									<div class="form-group">
										<label for="exampleInputEmail1"><?php echo $tr->translate("PHONE_EMAIL")?></label>
										<input type="text" class="form-control" id="email"  name="email" aria-describedby="emailHelp" placeholder="<?php echo $tr->translate("PHONE_EMAIL")?>">
										<small id="emailHelp" class=" display-none form-text text-muted">We'll never share your email with anyone else.</small>
									  </div>
									  <div class="form-group">
										<label for="exampleInputPassword1"><?php echo $tr->translate("PASSWORD")?></label>
										<input type="password" class="form-control" id="password"  name="password" placeholder="<?php echo $tr->translate("PASSWORD")?>">
									  </div>
									  <div class="form-group text-center">
										 <button type="submit" class="btn btn-primary btn-login"><span class="glyphicon glyphicon-lock"></span> <?php echo $tr->translate("LOGIN")?></button>
									  </div>
									 </form>
								</div>
								<div class="col-12 col-sm-3 col-md-3">
								</div>
							</div>
						</div>
						<div>
					</div>
				</div>
			</div>	
		
	
	
	

