<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("REPORT"));

$search = $this->search
?>

	
			
					<?php 
						echo $this->render('bloglogo.phtml');
					?>
					<div class="row">
						<div class="col-md-12 col-sm-12 col-xs-12 content-page-title">
							<h3 class="page-title"><span class="glyphicon glyphicon-folder-open"></span> <span class="sp-title"><?php echo $tr->translate("REPORT")?></span></h3>
						</div>
					</div>
					<div class="content-search">
					<form method="post">
						<div class="row row-form-group">
							<div class="form-group col-12 col-sm-6 col-md-2">
								<input type="text" class="form-control fullsize" name="search" value="<?php if (!empty($search['search'])){ echo $search['search'];}?>" placeholder="<?php echo $tr->translate("SEARCH")?>..." />
                            </div>
                            <div class="form-group col-12 col-sm-6 col-md-2">
                            	<select class="form-group js-select2 fullsize" id="document_type"  name="document_type" data-placeholder="<?php echo $tr->translate("SELECT_FROM_DOCUMENTTYPE");?>">
								  <?php if (!empty($this->opt)) foreach ($this->opt as $rs){?>
								  <option value="<?php echo $rs['id']?>" <?php if ($rs['id']==$search['document_type']){ echo 'selected="selected"';}?>><?php echo $rs['name']?></option>
								  <?php }?>
								</select>
                            </div>
                            <div class="form-group col-12 col-sm-6 col-md-2">
                            	<select class="form-group js-select2 fullsize" id="from_dept"  name="from_dept" data-placeholder="<?php echo $tr->translate("SELECT_FROM_DEPARTMENT");?>">
								  <?php if (!empty($this->opt)) foreach ($this->opt as $rs){?>
								  <option value="<?php echo $rs['id']?>" <?php if ($rs['id']==$search['from_dept']){ echo 'selected="selected"';}?>><?php echo $rs['name']?></option>
								  <?php }?>
								</select>
                            </div>
                            <div class="form-group col-12 col-sm-6 col-md-4">   
				                <div class="input-daterange input-group" id="date-range">
	                            	<input type="text" placeholder="<?php echo $tr->translate("START_DATE")?>..." class="form-control fullsize" name="start_date" value="<?php if (!empty($search['start_date'])){ echo date("m/d/Y",strtotime($search['start_date']));}?>" />
	                                <span class="input-group-addon b-0"><?php echo $tr->translate("TO");?></span>
	                                <input type="text" placeholder="<?php echo $tr->translate("END_DATE")?>..." class="form-control fullsize" name="end_date" value="<?php if (!empty($search['end_date'])){ echo date("m/d/Y",strtotime($search['end_date']));}?>" />
	                            </div>
                            </div>
                            
                            <div class="col-12 col-sm-6 col-md-2">
                            	<button type="submit" class="btn btn-primary btn-login"><span class="glyphicon glyphicon-search"></span> <?php echo $tr->translate("SEARCH")?></button>
                            </div>
                            <div class="clearfix">
                            </div>
			            </div>
					</form>
					</div>
					<div class="row">
						<div class="col-md-12 col-sm-12 col-xs-12">
							<div class="dataTables_scrollBody" style="position: relative; width: 100%; background:#fff;   ">
								<table border="1" id="datatable-responsive" style="  border-collapse: collapse; border-color: #ddd;"  class="display nowrap dataTable dtr-inline collapsed" cellspacing="0" width="100%" >
									<thead>
										<tr>
											<th class="text-center"><?php echo $tr->translate("NUM");?></th>
											<th class="text-center"><?php echo $tr->translate("DEPARTMENT_ADMIN_NO");?></th>
											<th class="text-center"><?php echo $tr->translate("FROM_DEPARTMENT");?></th>
											<th class="text-center"><?php echo $tr->translate("COMMENT");?></th>
											<th class="text-center"><?php echo $tr->translate("SCAN_DATE");?></th>
											<th class="text-center"><?php echo $tr->translate("SCAN_TYPE");?></th>
											<th class="text-center"><?php echo $tr->translate("PROCESS");?></th>
										</tr>
									</thead>
									<tbody>
										<?php if (!empty($this->row)) foreach ($this->row as $key => $rs){?>
										<tr class="row-odd">
											<td class="text-center"><?php echo $key+1?></td>
											<td><?php echo $rs['department_admin_no']?></td>
											<td><?php echo $rs['fromDept']?></td>
											<td style="width: 180px;overflow-wrap: break-word;white-space: normal;" ><?php echo $rs['comment']?></td>
											<td class="text-center"><?php echo date("d-m-Y H:i:s",strtotime($rs['scanDate']))?></td>
											<td class="text-center"><?php echo $rs['scanType']?></td>
											<td class="text-center"><?php echo $rs['proccess']?></td>
											
										</tr>
										<?php }?>
									</tbody>
								</table>
							</div>
						</div>
					<div>
				</div>
			</div>
		
	
	<link href="<?php echo $this->baseUrl()."/templates/";?>plugin/bootstrap-datepicker/css/bootstrap-datepicker.min.css" rel="stylesheet">
	<link href="<?php echo $this->baseUrl()."/templates/";?>plugin/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
	<link href="<?php echo $this->baseUrl()."/templates/plugin/select2/";?>css/select2.min.css" rel="stylesheet" />
	
	<script src="<?php echo $this->baseUrl()."/templates/plugin/"?>select2/js/select2.min.js"></script>	
	<script src="<?php echo $this->baseUrl()."/templates/";?>plugin/bootstrap-datepicker/js/bootstrap-datepicker.min.js"></script>
    <script src="<?php echo $this->baseUrl()."/templates/";?>plugin/bootstrap-daterangepicker/daterangepicker.js"></script>
    <style>
	.content-search {
		padding: 10px;
		margin-bottom: 10px;
		background: #f9f9f9;
		border: solid 1px #eeee;
	}
	.content-search .row.row-form-group {
		margin: 0;
	}
	.row.row-form-group div {
		padding: 0 2px;
		margin: 0;
	}
	span.input-group-addon.b-0 {
		padding: 0px 10px;
	}
	.select2-container--default .select2-selection--single {
		height: 40px;
		border-radius: 0;
		border: solid 1px #eee;
	}	
	.select2-container--default .select2-selection--single {
		padding: 5px;
		height: 40px;
		font-size: inherit;
		position: relative;
		border: 1px solid #ebebeb;
	}	
	.select2-container--default .select2-selection--single .select2-selection__arrow {
		height: 40px;
		position: absolute;
		top: -2px;
		right: 1px;
		width: 20px;
	}
</style>
<script>

$(function () {
	jQuery('#datepicker').datepicker();
	jQuery('#datepicker-autoclose').datepicker({
	    autoclose: true,
	    todayHighlight: true
	});
	jQuery('#date-range').datepicker({
	    toggleActive: true
	});

	 $(".js-select2").select2({
		  placeholder: "",
		  width: '100%'
		 
		});
});
</script>	
