<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("SCAN_CLOSE"));
?>

	
			
					<div class="main-content-scan">
					<?php 
						echo $this->render('bloglogo.phtml');
					?>
					<div class="row">
						<div class="col-12 col-sm-3 col-md-3">
						</div>
						<div class="col-12 col-sm-6 col-md-6">
							<div class="row">
								<div class="col-md-12 col-sm-12 col-xs-12 content-page-title">
									<h3 class="page-title"><span class="glyphicon glyphicon-qrcode"></span> <span class="sp-title"><?php echo $tr->translate("SCAN_CLOSE")?></span></h3>
									<h5 id ="messagescan" class="message_scan"></h5>
								</div>
							</div>
							<div class="container" id="QR-Code">
								<div class="panel panel-info panel-scan">
									<div class="panel-heading">
										<div class="navbar-form navbar-right">
											<select class="form-control" id="camera-select"></select>
											<div class="form-group display-none">
												<input id="image-url" type="text" class="form-control display-none" placeholder="Image url">
												<button title="Decode Image" class="btn btn-default btn-sm" id="decode-img" type="button" data-toggle="tooltip"><span class="glyphicon glyphicon-upload"></span></button>
												<button title="Image shoot" class="btn btn-info btn-sm disabled" id="grab-img" type="button" data-toggle="tooltip"><span class="glyphicon glyphicon-picture"></span></button>
												<button title="Play" class="btn btn-success btn-sm" id="play" type="button" data-toggle="tooltip"><span class="glyphicon glyphicon-play"></span></button>
												<button title="Pause" class="btn btn-warning btn-sm" id="pause" type="button" data-toggle="tooltip"><span class="glyphicon glyphicon-pause"></span></button>
												<button title="Stop streams" class="btn btn-danger btn-sm" id="stop" type="button" data-toggle="tooltip"><span class="glyphicon glyphicon-stop"></span></button>
											 </div>
										</div>
									</div>
									<div class="panel-body text-center">
										<div class="col-12 col-sm-12 col-md-12">
											<div class="well" style="position: relative;display: inline-block;">
												<canvas width="320" height="240" id="webcodecam-canvas"></canvas>
												<div class="scanner-laser laser-rightBottom" style="opacity: 0.5;"></div>
												<div class="scanner-laser laser-rightTop" style="opacity: 0.5;"></div>
												<div class="scanner-laser laser-leftBottom" style="opacity: 0.5;"></div>
												<div class="scanner-laser laser-leftTop" style="opacity: 0.5;"></div>
											</div>
											<div class="well" style="width: 100%; display:none">
												<label id="zoom-value" width="100">Zoom: 2</label>
												<input id="zoom" onchange="Page.changeZoom();" type="range" min="10" max="30" value="20">
												<label id="brightness-value" width="100">Brightness: 0</label>
												<input id="brightness" onchange="Page.changeBrightness();" type="range" min="0" max="128" value="0">
												<label id="contrast-value" width="100">Contrast: 0</label>
												<input id="contrast" onchange="Page.changeContrast();" type="range" min="0" max="64" value="0">
												<label id="threshold-value" width="100">Threshold: 0</label>
												<input id="threshold" onchange="Page.changeThreshold();" type="range" min="0" max="512" value="0">
												<label id="sharpness-value" width="100">Sharpness: off</label>
												<input id="sharpness" onchange="Page.changeSharpness();" type="checkbox">
												<label id="grayscale-value" width="100">grayscale: off</label>
												<input id="grayscale" onchange="Page.changeGrayscale();" type="checkbox">
												<br>
												<label id="flipVertical-value" width="100">Flip Vertical: off</label>
												<input id="flipVertical" onchange="Page.changeVertical();" type="checkbox">
												<label id="flipHorizontal-value" width="100">Flip Horizontal: off</label>
												<input id="flipHorizontal" onchange="Page.changeHorizontal();" type="checkbox">
											</div>
										</div>
										<div class="col-12 col-sm-12 col-md-12">
											<div class="thumbnail" id="result">
												<div class="well" style="overflow: hidden; display:none;">
													<img style="width: 100%;" height="240" id="scanned-img" src="">
												</div>
												<div class="caption display-none">
													<h3>Scanned result</h3>
													<p id="scanned-QR"></p>
												</div>
											</div>
										</div>
									</div>
								</div>	
							</div>
						</div>
						<div class="col-12 col-sm-3 col-md-3">
						</div>
							
						<div>
					</div>
				</div>
			</div>
	<script>
	var urlpart = "<?php echo $this->baseUrl();?>";
	var urlgo = '<?php echo $this->url(array('module'=>'','controller' => 'index','action' => 'scanning'));?>';
	</script>
	<link href="<?php echo $this->baseUrl()."/templates/";?>plugin/webcodecamjs/css/style.css" rel="stylesheet">
	<script type="text/javascript" src="<?php echo $this->baseUrl()."/templates/";?>plugin/webcodecamjs/js/qrcodelib.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl()."/templates/";?>plugin/webcodecamjs/js/webcodecamjs.js"></script>
	<script type="text/javascript" src="<?php echo $this->baseUrl()."/templates/";?>plugin/webcodecamjs/js/main.js"></script>
	<script>
	$(document).ready(function() {
		$('#play').click();
	});

	function scanDo(keyword){
		$( "#messagescan" ).html('');
		$.ajax({
			url: urlgo,
			data: {keyword: keyword,scantype: 3},
			type: "POST",
			success:function(data){
				
				if(data==0){
					$( "#messagescan" ).html('<?php echo $tr->translate("EMPTY_DATA_PLEASE_SCAN_AGAIN")?>');
				}else{
					$( "#messagescan" ).html('<?php echo $tr->translate("SCAN_CLOSE_SUCCESS")?>');
				}
			}

		});
	}
	</script>
		
	
	
	

