<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("DOCUMENT"));
$frm = $this->frm_search;
$urlEdit = $this->baseUrl()."/document/index/edit/id/";
$urlPrint = $this->baseUrl()."/report/index/prints/id/";
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-file-text" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('DOCUMENT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
				<div class="form-group"> 
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement("adv_search");?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('from_dept');?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('document_type');?>
					</div>
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('status');?>
					</div>
				</div>
				<div class="form-group">
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('start_date');?>
					</div> 
					<div class="col-md-3 col-sm-3 col-xs-12">
						<?php echo $frm->getElement('end_date');?>
					</div>
					
					<div class="col-md-3 col-sm-3 col-xs-12">
						<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?> 
		</div>
	</div>
</div>
<script src="<?php echo $this->baseUrl();?>/js/help.js"  type="text/javascript"></script>
<script type="text/javascript">
dojo.require("dojo.data.ItemFileWriteStore");  
dojo.require("dijit.form.DateTextBox");

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			if(key=="edit"){
				url='<?php echo $urlEdit;?>';
			}else if(key=="print"){
				url='<?php echo $urlPrint;?>';
			}
			gotoAction();
		},
		items: {
			"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
			"print": {name: "<?php echo $tr->translate("PRINT");?>", icon: "fa-print"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>
