<?php
	$tr = Application_Form_FrmLanguages::getCurrentlanguage();
	$this->headTitle($tr->translate('USER')); 
	echo $this->headTitle();
	
	$urlEdit = $this->baseUrl()."/rsvacl/user/edit/id/";
	$urlDelete = $this->baseUrl()."/rsvacl/user/delete/id/";
?>	
<style>
	#grid{
		margin: 0 auto;
	}
	.dojoxGridSortNode{
		text-align: center;	
		height: 30px;		
	}
</style>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-users" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('USER');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
		<div class="card-box">
			<form name="frmlist_users" action="<?php echo $this->url(array('module'=>'rsvacl','controller'=>'user','action'=>'index')); ?>" dojoType="dijit.form.Form" method="post">
				<div class="form-group"> 
					<div class="col-md-2 col-sm-2 col-xs-12">
						<input class="fullside" type="text" name="txtsearch" id="txtsearch" placeholder="<?php echo $tr->translate("SEARCH");?>"  dojoType="dijit.form.TextBox"
							 style="height: 30px;" value='<?php echo $this->txtsearch;?>'/>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<select class="fullside" name="user_type" id="user_type"  onChange="document.frmlist_agent.submit();" style=" height: 30px;" dojoType="dijit.form.FilteringSelect"> 
								<option value="-1" <?php if($this->user_type == -1) echo 'selected="selected"';?> ><?php echo $tr->translate("SELECT_USER_TYPE");?></option> 
								<?php foreach ($this->user_typelist as $key => $ut) : ?>
									<option value="<?php echo $ut['id'];?>" <?php if($ut['id'] == $this->user_type) echo 'selected'?>><?php echo $ut['name'];?></option>
								<?php endforeach;?>	 
							</select>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<select class="fullside" name="active" id="active"  onChange="document.frmlist_agent.submit();" style=" height: 30px;" dojoType="dijit.form.FilteringSelect"> 
								<option value="-1" <?php if($this->active == -1) echo 'selected="selected"';?> ><?php echo $tr->translate("SELECT_STATUS");?></option> 
								<?php foreach ($this->activelist as $key => $at) : ?>
									<option value="<?php echo $key;?>" <?php if($key == $this->active) echo 'selected'?>><?php echo $at;?></option>
								<?php endforeach;?>	 
							</select>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
						<button dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
					</div>
					<div class="col-md-2 col-sm-2 col-xs-12">
					</div>
				</div>
			</form>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script type="text/javascript">

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			if(key=="edit"){
				url='<?php echo $urlEdit;?>';
			}else if(key=="delete"){
				url='<?php echo $urlDelete;?>';
			}
			gotoAction();
		},
		items: {
			"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
			"delete": {name: "<?php echo $tr->translate("DELETE");?>", icon: "fa-trash"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>