<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
echo $this->headTitle($tr->translate("DEPARTMENT"));
$frm = $this->frm_zone;

$urlEdit = $this->baseUrl()."/other/department/edit/id/";
$urlDelete = $this->baseUrl()."/other/department/delete/id/";
?>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
               	<div class="col-sm-12 border-botom">
		    		<div class="col-sm-8 pd-0">
		    			<h4 class="m-b-0"><i class="fa fa-sitemap" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('DEPARTMENT');?></h4>
    			</div>
    			<div class="col-sm-4 text-right">
    			</div>
    		</div>
    	</div>
    	<div class="card-box">
    		<form id="list" name="list" action="" dojoType="dijit.form.Form" method="post">
	    		<div class="form-group"> 
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement("adv_search");?>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<?php echo $frm->getElement('search_status');?>
						</div>
						<div class="col-md-2 col-sm-2 col-xs-12">
							<button iconclass="dijitIconSearch" dojoType="dijit.form.Button" showLabel="true" type="submit"><?php echo $tr->translate("SEARCH");?></button>
						</div>
					</div>
    		</form>
    	</div>
    	<div class="card-box">
    		<div class="dataTables_scrollBody" style="position: relative;  width: 100%; background:#fff;   ">
    			<table border="1" id="datatable-responsive" style="  border-collapse: collapse;   border-color: #ddd;"  class="display nowrap dataTable dtr-inline collapsed" cellspacing="0" width="100%" >
    				<thead>
    					<tr>
    						<th class="tdheader text-center"><?php echo $tr->translate("NUM");?></th>
							<th class="tdheader text-center"><?php echo $tr->translate("CODE");?></th>
    						<th class="tdheader text-center"><?php echo $tr->translate("TITLE");?></th>
    						<th class="tdheader text-center"><?php echo $tr->translate("DATE");?></th>
    						<th class="tdheader text-center"><?php echo $tr->translate("STATUS");?></th>
    						<th class="tdheader text-center"><?php echo $tr->translate("BY_USER");?></th>
    					</tr>
    				</thead>
    				<tbody>
    					<?php $r=0; if (!empty($this->row)) foreach ($this->row as $rs){ 
    						if($r%2==0)$attb='normal';
    						else $attb='alternate';
    						$r++?>
    					<tr class="context-menu-one" oncontextmenu="setrowdata(<?php echo $rs['id']?>);return false;">
    						<td style="text-align:center;" ><?php echo $r;?></td>
							<td class="itesms" ><a class="edit" href="<?php echo $this->baseUrl()."/other/department/edit/id/".$rs['id'];?> "><?php echo $rs['code']?></a></td>
    						<td class="itesms" ><a class="edit" href="<?php echo $this->baseUrl()."/other/department/edit/id/".$rs['id'];?> "><?php echo $rs['title']?></a></td>
    						<td class="itesms" ><a class="edit" href="<?php echo $this->baseUrl()."/other/department/edit/id/".$rs['id'];?> "><?php echo date("d-M-Y H:i:s",strtotime($rs['modify_date']))?></a></td>
    						<td class="itesms text-center" ><?php echo $rs['status']?></td>
    						<td class="itesms" ><a class="edit" href="<?php echo $this->baseUrl()."/other/department/edit/id/".$rs['id'];?> "><?php echo $rs['user_name']?></a></td>
    						
    					</tr>
    					<?php }?>
    				</tbody>
    			</table>
    		</div>	
    	</div>
    </div>
</div>
<script type="text/javascript">

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			if(key=="edit"){
				url='<?php echo $urlEdit;?>';
			}else if(key=="delete"){
				url='<?php echo $urlDelete;?>';
			}
			gotoAction();
		},
		items: {
			"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
			"delete": {name: "<?php echo $tr->translate("DELETE");?>", icon: "fa-trash"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>
