<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$urlEdit = $this->baseUrl()."/rsvacl/usertype/edit/id/";
$urlDelete = $this->baseUrl()."/rsvacl/usertype/delete/id/";
?>
<title><?php echo $tr->translate("USER_TYPE")?></title>
<div class="card pb-10 pt-10 pl-10 pr-10">
	<div class="card-content collapse show">
		<div class="card-box">
			<div class="col-sm-12 border-botom">
				<div class="col-sm-8 pd-0">
					<h4 class="m-b-0"><i class="fa fa-sitemap" aria-hidden="true"></i>&nbsp;&nbsp;&nbsp;<?php echo $tr->translate('USER_TYPE');?></h4>
				</div>
				<div class="col-sm-4 text-right">
				</div>
			</div>
		</div>
		<div class="card-box">
			<?php echo $this->list;?>
		</div>
	</div>
</div>
<script type="text/javascript">

var row=0;
var url="";
$(function(){
	$.contextMenu({
		selector: '.context-menu-one', 
		callback: function(key, options) {
		
			var m = "clicked: " + key;
			if(key=="edit"){
				url='<?php echo $urlEdit;?>';
			}else if(key=="delete"){
				url='<?php echo $urlDelete;?>';
			}
			gotoAction();
		},
		items: {
			"edit": {name: "<?php echo $tr->translate("EDIT");?>", icon: "edit", accesskey: "e"},
			"delete": {name: "<?php echo $tr->translate("DELETE");?>", icon: "fa-trash"},
		}
	});
});
function setrowdata(index){
	row = index;
}
var recordid ='';
function gotoAction(){
	 window.open(url+row, '_blank');
}
</script>