<?php 
$tr = Application_Form_FrmLanguages::getCurrentlanguage();
$key = new Application_Model_DbTable_DbKeycode();
$datasetting =$key->getKeyCodeMiniInv(TRUE);
$logo = $this->baseUrl()."/public"."/images/photo/logo/Logo.png";
if (!empty($datasetting['logo'])){
	if (file_exists(PUBLIC_PATH."/images/photo/logo/".$datasetting['logo'])){
		$logo = $this->baseUrl()."/public"."/images/photo/logo/".$datasetting['logo'];
	}
}
?>
<html>
<head>
<link rel="shortcut icon" href="<?php echo $this->baseUrl();?>/public/images/icon.ico" type="image/x-icon"/>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">	
<link href="<?php echo $this->baseUrl()."/public/"?>dashboard/notFoundPage/style.css" rel="stylesheet">
<title><?php echo  $tr->translate("Page Not Found");?></title>
</head>
	<body>
		<div class="wrapper row2">
		  <div id="container" class="clear">
		    <section id="fof" class="clear">
		      <div class="hgroup">
		      	<img src="<?php echo $logo;?>" style="width: 140px;" />
		      	 <?php $ise = 0; if ($ise==1){?>
		        <h1><span><strong>4</strong></span><span><strong>0</strong></span><span><strong>4</strong></span></h1>
		        <?php }?>
		        <h2><?php echo  $tr->translate("Sorry");?> ! <span><?php echo $tr->translate("This page is not found in our site");?></span></h2>
		      </div>
		      <p><?php echo $tr->translate("Please Try Again");?> !</p>
		      <p><a href="javascript:history.go(-1)">&laquo; <?php echo $tr->translate("GO_BACK");?></a> / <a href="<?php echo $this->baseUrl()."/";?>"><?php echo $tr->translate("Go Home");?> &raquo;</a></p>
		    </section>
		  </div>
		</div>
	</body>
</html>